USE [GiuaKy]
ALTER TABLE [dbo].[Payment] REBUILD PARTITION = 1 WITH(DATA_COMPRESSION = ROW )
USE [GiuaKy]
ALTER TABLE [dbo].[Payment] REBUILD PARTITION = 2 WITH(DATA_COMPRESSION = ROW )
USE [GiuaKy]
ALTER TABLE [dbo].[Payment] REBUILD PARTITION = 3 WITH(DATA_COMPRESSION = ROW )
